version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm ci
      - npm run build || echo "no client build step"
artifacts:
  files:
    - '**/*'
  discard-paths: no
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - .github/**/*
    - .gitignore
    - README.md
