version: 0.2
phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      - npm run build || echo "no build step"
artifacts:
  files:
    - '**/*'
  discard-paths: no
